### ISSUE TITLE
My page is not exactly the same with the mock view

### ISSUE THREAD

**Issue by nonso82** [jhu-ep-coursera/fullstack-course4#121]
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
<link rel="stylesheet" type="text/css" href="style.css">
	<title>Module2-Solution</title>
<style>
@media (min-width: 992px) {
	.column {
		width: 33.33%;
	}
}

@media (min-width: 767px) and (max-width: 991px) {
	.column {
		width: 50%;
	}
}

	@media (max-width: 768px) {
	.column {
		width: 100%;
	}
}
</style>
</head>
<body>

<h1>Web Development Technologies</h1>
<div class="column"><p id="col1">Html</p><h4>Hyper Text Mark Up  that defines the structure of our web page. In otherwords,it lay the foundation of our web pages</h4></div>

<div class="column"><p id="col2">Css</p><h4>Cascading Style Sheet is one of the web technologies that helps us to apply different styles to our web pages.With Cascading style sheets,our web sites look attractive and appealing to users</h4></div>

<div class="column"><p id="col3">JavaScript</p><h4>JavaScript Language is a programming language that is most popular</h4></div>

</body>
</html>

**Comment by ychaikin** [comment]
This isn't a forum to ask questions. Ask your question on the Coursera course forum.
