### ISSUE TITLE
Complete lecture slides

### ISSUE THREAD

**Issue by thuyihan1206** [jhu-ep-coursera/fullstack-course4#14]
I am just copying my comment on [Coursera](https://www.coursera.org/learn/html-css-javascript-for-web-developers/discussions/VO75Xe1CEeWPKQpBKpg03Q) to here for your convenience.

> I realized that the lecture slides hosted at [GitHub](https://github.com/jhu-ep-coursera/fullstack-course4/tree/master/Lecture-Slides) are not complete. For example, for Week 1, it misses lectures 4, 7, 9, and 10. I understand some of these lectures are majorly demo based, but I would still love to at least include the summary slide at the end of each lecture to my collection.
> 
> Thanks!
> 
> Evan

**Comment by JReeGene** [comment]
Also noted. The slides 4,7,9, and 10 are missing.

**Comment by ychaikin** [comment]
Added missing PDF lecture slides.
