### ISSUE TITLE
Submissions

### ISSUE THREAD

**Issue by khalilsayhi** [jhu-ep-coursera/fullstack-course4#148]
Git no longer has a gh pages button so how can we submit our work? the clone link always refers to the master branch!

**Comment by ychaikin** [comment]
Please ask questions in the Coursera forum. See the FAQ for your particular question.
https://github.com/jhu-ep-coursera/fullstack-course4/blob/master/FAQ.md

**Comment by aman9411** [comment]
Sir i can’t access the correct webpage according to my media query code please help

**Comment by ychaikin** [comment]
@aman9411 Come on, seriously. There is a message right above this one that tells you to ask on the forum.
