### ISSUE TITLE
In assignments/assignment5/snippets/home-snippet.html

### ISSUE THREAD

**Issue by geeky1Coder** [jhu-ep-coursera/fullstack-course4#165]
Line number 10 is throwing a syntax error.
10.<a href="#" onclick="$dc.loadMenuItems({{randomCategoryShortName}});">

**Comment by nitigna-ui** [comment]
Sir i have some issues so can i submit assignment after two days?

**Comment by ychaikin** [comment]
@geeky1Coder There are no issues with the code.

@nitigna-ui Ask questions on the Coursera forum.

**Comment by Rakib366** [comment]
I can't understand what can i do there..😥
