### ISSUE TITLE
after setting the branch as "Master Branch". the index.html file, CSS file and paramjs file are not available.please provide me the solution for that

### ISSUE THREAD

**Issue by Shivani6163** [jhu-ep-coursera/fullstack-course4#167]
This is NOT the place to ask questions about the material or your issues with assignments from the Coursera course.

If you have a question or an issue, use the Coursera forum to ask that. Make the question as detailed as possible so people don't have to ask you for more details before answering your question.

Questions posted here as issues will simply be closed.

**Comment by Shivani6163** [comment]
after setting the branch as "Master Branch". the index.html file, CSS file and paramjs file are not available.please provide me the solution for that

**Comment by Shivani6163** [comment]
after setting the branch as "Master Branch". the index.html file, CSS file and paramjs file are not available.please provide me the solution for that

**Comment by Shivani6163** [comment]
after setting the branch as "Master Branch". the index.html file, CSS file and paramjs file are not available.please provide me the solution for that

**Comment by ychaikin** [comment]
Stop using this as question answer forum.
