### ISSUE TITLE
Course era web development

### ISSUE THREAD

**Issue by Adarsh2k20** [jhu-ep-coursera/fullstack-course4#176]
This is NOT the place to ask questions about the material or your issues with assignments from the Coursera course.

If you have a question or an issue, use the Coursera forum to ask that. Make the question as detailed as possible so people don't have to ask you for more details before answering your question.

Questions posted here as issues will simply be closed.

**Comment by ychaikin** [comment]
@Adarsh2k20 Did you not read the message that's part of this issue??
