### ISSUE TITLE
about the model 5 i do not understand

### ISSUE THREAD

**Issue by mohammed-web** [jhu-ep-coursera/fullstack-course4#179]
This is NOT the place to ask questions about the material or your issues with assignments from the Coursera course.

If you have a question or an issue, use the Coursera forum to ask that. Make the question as detailed as possible so people don't have to ask you for more details before answering your question.

Questions posted here as issues will simply be closed.

**Comment by ychaikin** [comment]
@mohammed-web Seriously? 🤷
