### ISSUE TITLE
Incorrect use of 'alt' attribute

### ISSUE THREAD

**Issue by ychaikin** [jhu-ep-coursera/fullstack-course4#18]
Lecture 30, part 1, I left an alt attribute right inside of a 'div'. Must have been a leftover from messing around with it off screen and then I "talked right through it", forgetting that there is no such thing as an 'alt' attribute for a div tag.

Fix and edit out of the video.

**Comment by pascArr** [comment]
Thanks for letting us know. Nice call!

Btw this course has been a life changing for me. Thanks for putting it together. I will definitely enroll to the advance part of it. 

Keep on the amazing work!! 

Pascual Arrechea

**Comment by ychaikin** [comment]
Actually, a couple of the students pointed this out. I didn't notice it. :-)

-Yaakov.

**Comment by ychaikin** [comment]
[Fixed](https://github.com/jhu-ep-coursera/fullstack-course4/commit/b335669a02dfddf127033555a3ec43d6b2c0d9fb)
