### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by surendra-sketch** [jhu-ep-coursera/fullstack-course4#194]
Sir it seems I'm not able to create a website with .io extension , how to create to submit for my assignment.please help me sir! Although I have already created a GitHub account.

**Comment by ashukumar2001** [comment]
First you need to make a repository of like this :- YourUsername.github.io
And then make another repo for your assignment solution and then upload your index.html to this repository. Now go to setting and scroll down here you can see GitHub pages and url of you website.

**Comment by surendra-sketch** [comment]
It would be better if you could send me screenshot for only create the web
with .io extension. By the way thanks a lot for your support.

**Comment by ashukumar2001** [comment]
See my profile

**Comment by surendra-sketch** [comment]
> See my profile

Thank you so much bro!

**Comment by ychaikin** [comment]
@surendra-sketch @ashukumar2001 This is not a forum. There IS a forum that is part of the Coursera course. Please DO NOT post questions like these (or the answers) to this repository.
