### ISSUE TITLE
Module 4

### ISSUE THREAD

**Issue by Naana-sark** [jhu-ep-coursera/fullstack-course4#195]
The module 4 assignment, before I submitted it on Github and I run it, it worked. but once I submitted it on GitHub and I checked console it says it can not open the speakGoodbye.js file even though I uploaded it. Here is the link please https://naana-sark.github.io/coursera-test/module4/index.html

**Comment by ychaikin** [comment]
@Naana-sark So, you decided to ignore the clear message that was part of the "new issue" template where it says not to post issues here that are really just questions you should be posting to the Coursera forum?
