### ISSUE TITLE
Assignment 5 Summary doesn't match the instructions in script.js

### ISSUE THREAD

**Issue by jorarcar** [jhu-ep-coursera/fullstack-course4#214]
In assignment 5.md, there is a mismatch between what you were requesting in the summary text, and what is doing the js code. In the summary text, the random single category menu will appear when the user clicks on the specials tile. But, in the script.js, all the code is built to load this random single category in the home HTML instead.

I think the summary should be updated accordingly, to avoid confusion.

Summary of the Assignment:
![image](https://user-images.githubusercontent.com/23691079/91527509-85433200-e8cb-11ea-9a30-76719ce6d321.png)

Current instructions in script.js:
![image](https://user-images.githubusercontent.com/23691079/91527528-8f653080-e8cb-11ea-8b06-0ff20779c257.png)

**Comment by ychaikin** [comment]
Read the task again carefully. There is no mismatch.
