### ISSUE TITLE
From Coursera class

### ISSUE THREAD

**Issue by Saint-Dave** [jhu-ep-coursera/fullstack-course4#238]
This is NOT the place to ask questions about the material or your issues with assignments from the Coursera course.

If you have a question or an issue, use the Coursera forum to ask that. Make the question as detailed as possible so people don't have to ask you for more details before answering your question.

Questions posted here as issues will simply be closed.

**Comment by Amani76828** [comment]
Sorry😊😊

في السبت، ٣١ أكتوبر ٢٠٢٠ ٤:٤٧ م Saint-Dave <notifications@github.com> كتب:
