### ISSUE TITLE
After file - Lesson 33

### ISSUE THREAD

**Issue by sebautistam** [jhu-ep-coursera/fullstack-course4#243]
Hello!

I've been coding alongside the videos the restaurant website, without any issue so far. However, after ending lesson 33, I noticed that the "after" HTML file has an added button for the XS screen sizes that is not shown during the lectures (We Deliver button), and lesson 34 begins its coverage from the jumbotron, so this button is already placed. I double checked lesson 33 and I couldn't find the explanation about the CSS and HTML coding for this button, which is in fact important.

The HTML part is:

`
<div id="call-btn" class="visible-xs">
    <a class="btn" href="tel:410-602-5008">
      <span class="glyphicon glyphicon-earphone"></span>
      410-602-5008
    </a>
  </div>
  <div id="xs-deliver" class="text-center visible-xs"> * We Deliver </div>
`

And the CSS is:

 `#call-btn > a {
		font-size:1.5 em;
		display: block;
		margin: 0 20px;
		padding: 10px;
		border: 2px solid #fff;
		background-color: #f6b319;
		color: #951c49;
	}

	#xs-deliver {
		margin-top: 5px;
		font-size: 0.7em;
		letter-spacing: 0.1em;
		text-transform: uppercase;
	}`

Am I missing something, or is actually a part missing?

Thank you!

**Comment by ychaikin** [comment]
It's possible that it's missing from the videos, but it's not a big deal and there is nothing in this code that we haven't covered.
