### ISSUE TITLE
i can't install Git on my Macbook Pro

### ISSUE THREAD

**Issue by erwinoli99** [jhu-ep-coursera/fullstack-course4#244]
i can't install Git on my Macbook pro. i have nodejs install, i have nodejs install, sublime text install, i also have Git downloaded but when i go to the terminal and i type the comand $git--version, the files can't be found, i would like to know what i didn't do.

**Comment by ychaikin** [comment]
So, you decided to erase the note that specifically says not to ask questions here and that any such questions will be erased,  and then proceeded to ask a question?  🤔
