### ISSUE TITLE
not able to load nav bar in code snippet

### ISSUE THREAD

**Issue by kuhukrasrogi** [jhu-ep-coursera/fullstack-course4#245]
**Here is my code, while executing the nav bar isn't getting displayed.**
Please help, resolve  my issue.

<body>
	<p>paragar</p>
	<header>
		<nav id="header-nav" class="navbar navbar-default">
			<div class="container">
			</div>
		</nav>
	</header>

link for GITHUB repo -- **<https://github.com/kuhukrasrogi/assign_issues/blob/main/index1.html>**

**Comment by ychaikin** [comment]
The comment in the template for creating an issue in this repository specifically said NOT to ask questions here. Ask them on the Coursera forum.
