### ISSUE TITLE
regarding the assignment

### ISSUE THREAD

**Issue by dannylai-cloud** [jhu-ep-coursera/fullstack-course4#252]
To whom may it concern 

   I am writing this email in reference to encounter some issue cannot solve by myself  , please gimme a hand , i really tried many times and still stuck and cannot find the solution, i would like forward to hearing from you.
with attachment

kind regards 
Danny Lai

**Comment by dannylai-cloud** [comment]
![Web capture_16-1-2021_231923_](https://user-images.githubusercontent.com/76635809/104815836-15b9e900-5852-11eb-8de0-77239f8586ea.jpeg)

**Comment by ychaikin** [comment]
As the issue template stated, don't create issues here to ask a question. Use Coursera's forum.
