### ISSUE TITLE
Bug: Blur event doesn't fire on Safari and Firefox

### ISSUE THREAD

**Issue by ychaikin** [jhu-ep-coursera/fullstack-course4#28]
In mobile view, we have code that automatically closes the slide down menu when the user click anywhere else on the page. We use `blur` event for that.

However, on Firefox and Safari, the `blur` event never fires because the slide down menu button only receives the click even to slide the menu down, but it does not retain focus, so the `blur` event is useless.

On Chrome, this is not an issue because the button does retain focus after it's clicked. 
[Here is the code in question](https://github.com/jhu-ep-coursera/fullstack-course4/blob/master/examples/Lecture59/after/js/script.js#L4l).

Whatever the solution, it needs to be carried through to the rest of the lecture examples in the course.

**Comment by ychaikin** [comment]
@freeranger Came up with a quick fix:
```
  $("#navbarToggle").click(function (event) {
  	$(event.target).focus();
  });
```
The following [MDN Article discusses the issue](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Button#Clicking_and_focus).

Still need to update in the code, comment it well (maybe referring back to this ticket) and carry it forward to other lecture examples until the end of the course.

**Comment by freeranger** [comment]
Do you want me to add that as a PR to the codebase, or do you want to do it all?
More than happy with the latter but also willing to do the former ;)

**Comment by ychaikin** [comment]
@freeranger Thank you for the offer! I had to write the comment already anyway, so I figured I'll spend an extra few minutes updating it and testing. It's in there now. Thank you!
[Resolved](https://github.com/jhu-ep-coursera/fullstack-course4/commit/c86407aef4106fa679e3fe6327598768b8ec9212)

**Comment by freeranger** [comment]
Sure, no problem.
Incidentally I asked a room full of seasoned web developers if a button gets the focus when you click on it and they all got it wrong - so it's not just you who makes entirely reasonable assumptions ;)

**Comment by jasonwr** [comment]
@freeranger interesting... Keep in mind when you say button this can either mean the button element or the input element with type set to button. The following **onfocus** triggers when the button is clicked:

`<!DOCTYPE html>
<html>
<body>

<form> 
  <button onfocus="another_msg()">Just a button</button> 
</form>

<p>Click the above button. Go ahead, just click it.</p>

<script>
function another_msg() {
  alert("Just wanted to let you know that I'm focused!");
}
</script>
</body>
</html>`

I'm running Firefox 46 for Windows 7 and when the page renders I see a dotted line around the text within the button. This implies the button is focused and I also get the alert from the another_msg function. Also if I place the new HTML5 autofocus attribute in the button element then the another_msg function is triggered when the page loads and you'll even notice a small dotted line around the text in the button if your running FF 46 on Windows 7. I haven't tested other browsers.

**Comment by ychaikin** [comment]
@freeranger Actually, I am on the fence as to whether the correct behavior should be to retain the focus on click or not. Clearly, the browsers disagree, so I doubt there is a right and a wrong answer to this.

Your solution forces it to be one way: to keep the focus. Certainly reasonable. I was thinking of implementing something that catches a click event _anywhere_ on the page and just checks if the state of the slidedown is down or up. If down, make it go away. That way, we can let the browsers fight it out as to what the correct way is and not get in the middle of it.

Coincidentally, if you open Chrome and Safari side by side with the current solution and browser-sync going, you will get into this funny situation where one browser is closing the slidedown while the other one opens it. :-)

However, for this class, I think I'd leave it as is (with your solution). The other one would deviate too much from the existing code and night confused people.

**Comment by freeranger** [comment]
@jasonwr There is no page there to try, but according to this (which led me to the solution) https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Button#Clicking_and_focus
The problem happens with button and input type=button

@ychaikin I got an email from GitHub with a response from you on this issue but I can't see it in GitHub itself which is a bit weird.  You said you are on the fence with the solution.  I think it is entirely reasonable and to be expected that a button gets the focus when you click on it, just as a text input for example would get the focus - how else is that thing to receive user input unless it has the focus?
My solution ensures that it gets the focus so that it can then lose the focus when you click on something else (or tab away).  It does not hang onto the focus when you try to move away from it, so I can't see any nasty side effects from doing this.  I may be wrong of course and there is some edge case I haven't thought of....

**Comment by jasonwr** [comment]
@freeranger wait I'm confused. Did you see the source (HTML) I pasted? Copy/paste that into an html file and open it up in FF.

**Comment by freeranger** [comment]
This is what I see in your post:

`<!DOCTYPE html>

Just a button
Click the above button. Go ahead, just click it.


`

**Comment by jasonwr** [comment]
@freeranger that's not accurate. Try clearing your browser cache. I'm seeing this:

![prtscn_jsnrice](https://cloud.githubusercontent.com/assets/305999/16503262/4eefbaa0-3ee0-11e6-95b4-57e468df32cb.png)

**Comment by freeranger** [comment]
@jasonwr I've just tried it on FireFox 47.0.1 and Safari 9.1.1 on the Mac and in neither case was the message displayed.
In Chrome however, it was.
If it did work, I'm not sure how valid a test it is anyway - with only one control on the page, there is nothing else that could have the focus...except the window itself I guess - but in any event, on OSX it does not behave as expected, which is exactly what it tells you here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Button#Clicking_and_focus
