### ISSUE TITLE
Lecture 25, part 2: Bootstrap ,CSS and  jQuery page does not show up on Sublime 

### ISSUE THREAD

**Issue by Pankaj2802** [jhu-ep-coursera/fullstack-course4#288]
Hello Yaakov,

At first I'm not getting all those folder in my Sublime text like you do in all the video lectures. How to link all the html,css files to sublime- it says unregistered attched screenshot- https://ibb.co/RcjDbsT?
Second, I am facing challange in Lecture 25, I have download the bootstrap and extract the file to computer as well whereas the bootstrap file does not show up on my sublime.
Third, I am no able to download or save the JS query from website (https://jquery.com/download/), when clicked on this link " Download the compressed, production jQuery 3.6.0 " it shows some code in next page but could not saved it.  -https://ibb.co/Pw3KN21

Attached the screenshot for your refernce. Please help

**Comment by ychaikin** [comment]
As the issue template stated, this is not the place to ask questions about the course.
