### ISSUE TITLE
Toogle Button not working 

### ISSUE THREAD

**Issue by Pankaj2802** [jhu-ep-coursera/fullstack-course4#289]
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#collapsable-nav" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
  </div>
      	<div id="collapsable-nav" class="collapse navbar-collapse">
      		<ul id="nav-list" class="nav navbar-nav navbar-right">
      			<li>
      				<a href="menu-categories.html">
      					<span class="glyphicon glyphicon-cutlery"></span>
      					<br class="hidden-xs"> Menu</a>
      				</li>
      				<li>
      				<a href="#">
      					<span class="glyphicon glyphicon-info-sign"></span>
      					<br class="hidden-xs"> About</a>
      				</li>
      				<li>
      				<a href="menu-categories.html">
      					<span class="glyphicon glyphicon-certificate"></span>
      					<br class="hidden-xs"> Awards</a>
      				</li>
      				<li id="phone" class="hidden-xs">
      					<a href="tel:410-602-5008">
      						<span> 410-602-5008</span></a><div>* We Deliver</div>
      					</li>
      				</ul>
      			</div>
      		</div>
![Screenshot (4)](https://user-images.githubusercontent.com/86179475/125792743-be091395-2187-4a02-b4e5-7f64de670123.png)

**Comment by ychaikin** [comment]
Not sure what specific version of the site you are referring to, but the menu is working as expected at the point of the course when we finished it.
