### ISSUE TITLE
Module 1 quiz

### ISSUE THREAD

**Issue by Sovereign-X0** [jhu-ep-coursera/fullstack-course4#292]
Answers for questions 9 and 12 for the end of module quiz are not rendering. Have had no issues with any of the previous quizzes within the module, so this is particularly vexing.

**Comment by ychaikin** [comment]
@Sovereign-X0 Thanks for reporting that. Can you please scroll down to the bottom of that quiz page and click the flag icon on the right and then report the issue to Coursera. This is a Coursera platform issue and I don't think I can do anything about that.
