### ISSUE TITLE
FAQ doesn't seem to have latest Git behavior.

### ISSUE THREAD

**Issue by Annamarie2019** [jhu-ep-coursera/fullstack-course4#309]
This is the best I could gather from the FAQ, since Git behavior seems to have changed even after this FAQ. It did not have simply a publish page, but seemed to force me to select a theme, which I don't think we want right now. Should I remove it? How do I remove it?

There was also no "master," so it seemed like "main" must be the latest iteration of that. Here's what I have, in the "main" folder, an extra docs folder with the index and the theme:
<img width="639" alt="DocsFolderwithTheme" src="https://user-images.githubusercontent.com/46230706/145296014-9da468d5-185d-4719-90fd-72562dad267a.png">

It contains the YML config file and the index:

<img width="400" alt="YMLConfigandIndex" src="https://user-images.githubusercontent.com/46230706/145297164-c82b1cb2-2dd3-4aaf-ac3b-067fb1f7cec1.png">

and the YML config only has the theme in it:
<img width="447" alt="Theme" src="https://user-images.githubusercontent.com/46230706/145298138-c18ddf21-62a3-4430-9a9a-a13d3f2277a1.png">

Should I delete the YML Config?

**Comment by Annamarie2019** [comment]
I remembered how to delete a file, so I deleted the _config.yml. Now there's only an index.md in the folder, which, I'm hoping, is where we want to start from a clean slate.

**Comment by ychaikin** [comment]
I updated the FAQ to reflect the latest GitHub changes.
