### ISSUE TITLE
Can't find automatic page generator

### ISSUE THREAD

**Issue by salmangood** [jhu-ep-coursera/fullstack-course4#315]
Hi,sir I try to find automatic page generator in GitHub.but don't have automatic page generator option any more so to do now ??
![Screenshot_2021-12-29-13-52-49-08](https://user-images.githubusercontent.com/96780705/147631602-3206545f-1e01-4801-8ab2-bb61662c7474.jpg)

**Comment by ychaikin** [comment]
This is the text you erased before posting the issue:
```
This is NOT the place to ask questions about the material or your issues with assignments from the Coursera course.

If you have a question or an issue, use the Coursera forum to ask that. Make the question as detailed as possible so people don't have to ask you for more details before answering your question.

Questions posted here as issues will simply be closed.
```

Also, see the FAQ: https://github.com/jhu-ep-coursera/fullstack-course4/blob/master/FAQ.md
