### ISSUE TITLE
Heading Text in navbar not moving to right of logo

### ISSUE THREAD

**Issue by Niyathi-MobileNext** [jhu-ep-coursera/fullstack-course4#316]
Even if I use `class="pull-left visible-md visible-lg">`, I cannot move the text to the right side of logo. It still appears under the logo. Could you please let me know what was the issue? I am also attaching a scrennshot herewith for reference.

My Code(same as in class): 
`<body>
        <header>
            <nav id="header-nav" class="navbar navbar-default">
                <div class="container">
                    <div class="navbar-header">
                        <a href="index.html" class="pull-left visible-md visible-lg">
                          <div id="logo-img"></div>
                        </a>
                        <div class="navbar-brand">
                            <a href="index.html">
                                <h1>David Chu's China Bistro</h1>
                            </a>
                            <p>
                                <img src="images/star-k-logo.png" alt="Kosher Certification">
                                <span>Kosher Certified</span>
                            </p>
                        </div>
                    </div>
                </div>
            </nav>
        </header>
        <script src="js/jquery-3.6.0.min.js"></script>
        <script src="js/bootstrap.min.js"></script>
        <script src="js/script.js"></script>
    </body>`.

I also tried `<nav id="header-nav" class="navbar navbar-expand-lg navbar-light " role="navigation">` as the bootstrap classes has been updated from the time this video was shot. but still I could see no use. Please help

![image](https://user-images.githubusercontent.com/72200491/148786772-85110e8c-1fad-478d-a889-9f2a99098298.png)

**Comment by ychaikin** [comment]
From the issue template for this repository:
This is NOT the place to ask questions about the material or your issues with assignments from the Coursera course.

If you have a question or an issue, use the Coursera forum to ask that. (BUT FIRST, check the FAQ for the course: https://github.com/jhu-ep-coursera/fullstack-course4/blob/master/FAQ.md) Make the question as detailed as possible so people don't have to ask you for more details before answering your question.

Questions posted here as issues will simply be closed.
