### ISSUE TITLE
Why terminal doesn't recognize the command?

### ISSUE THREAD

**Issue by Justivp** [jhu-ep-coursera/fullstack-course4#318]
When I open terminal with win+r and put command:
"C:\Users\Acer>[yaakov coursera]$ git clone https://github.com/Justivp/coursera-test.git"

I get the answer:
 "[yaakov' is not recognized as an internal or external command, operable program or batch file." 

Please help me. My link is: https://justivp.github.io/coursera-test/ 
Thank you

**Comment by ychaikin** [comment]
As the issue template stated:

This is NOT the place to ask questions about the material or your issues with assignments from the Coursera course.

If you have a question or an issue, use the Coursera forum to ask that. (BUT FIRST, check the FAQ for the course: https://github.com/jhu-ep-coursera/fullstack-course4/blob/master/FAQ.md) Make the question as detailed as possible so people don't have to ask you for more details before answering your question.

Questions posted here as issues will simply be closed.
