### ISSUE TITLE
Bootstrap version is out of date for 2022

### ISSUE THREAD

**Issue by VictoriaMW1010** [jhu-ep-coursera/fullstack-course4#331]
The Bootstrap version being used in the course is very out of date, making assignments impossible to complete with the provided materials and requiring self-teaching to actually complete with the newest Bootstrap version, since the instructions are also outdated.

**Comment by ychaikin** [comment]
Use the bootstrap version that the course teaches. The concepts are the same, just how they are implemented are slightly different.

**Comment by VictoriaMW1010** [comment]
Thank you so much for responding! This would be completely fine except that the breakpoints are different. The assignment asks that:
"-Desktop mockup illustration should correspond to Bootstrap md-based classes
-Tablet mockup illustration should correspond to Bootstrap sm-based classes
-Mobile mockup illustration should correspond to Bootstrap xs-based classes,"

But col-md-4's breakpoint in the Bootstrap version the course provides is 992 pixels instead of 768. This means that if I use the Bootstrap version from the course, the layout at e.g. 900 pixels -- considered "desktop" if desktop equals md-based -- is 2-col instead of 3-col. This was genuinely driving me crazy because I could not figure out what was wrong with my code until I checked the breakpoint and then plugged in Bootstrap from getbootstrap.com.

If students should adhere to the breakpoints as provided in the Bootstrap from the course, and not the breakpoints for desktop/tablet/mobile or md/sm/xs as defined anywhere online, it would be helpful at least for students like myself if the instructions could make this clearer.

Thank you again!

**Comment by ychaikin** [comment]
@VictoriaMW1010 Bootstrap version used in the course did not change its breakpoints for the same bootstrap version. Just stick to the version in the course and don't mix one version with another.
