### ISSUE TITLE
The Bootstrap grid/column system doesn't on my site. I am now behind with the course material and currently stuck on week two of HTML, CSS, and Javascript for Web Developers on the coding assignment. This is because, for some odd reason, even after following all the lectures instructions step by step, the Bootstrap column feature does not work on my website. Please help so I can catch up on the new course material. 

### ISSUE THREAD

**Issue by Filletmignon** [jhu-ep-coursera/fullstack-course4#339]
Filletmignon, 

I am now behind with the course material and currently stuck on week two of HTML, CSS, and Javascript for Web Developers on the coding assignment. This is because, for some odd reason, even after following all the lecture's instructions step by step, the Bootstrap column feature does not work on my website. Please help so I can catch up on the new course material. 

Here is a link to my repository : https://github.com/Filletmignon/Module2-Solution.git
Here is a link for my website : http://localhost:3000/Module2.html

Thank you,

**Comment by ychaikin** [comment]
You decided to ignore what was written in the template when you created this issue? The template that said "Use this template!"

Here are the contents reposted:
This is NOT the place to ask questions about the material or your issues with assignments from the Coursera course.

If you have a question or an issue, use the Coursera forum to ask that. (BUT FIRST, check the FAQ for the course: https://github.com/jhu-ep-coursera/fullstack-course4/blob/master/FAQ.md) Make the question as detailed as possible so people don't have to ask you for more details before answering your question.

Questions posted here as issues will simply be closed.
