### ISSUE TITLE
Lecture 25, part 2: jQuery page shown is different

### ISSUE THREAD

**Issue by ychaikin** [jhu-ep-coursera/fullstack-course4#34]
jQuery 3.x has come out since then and some people may get confused about where to go to download version 2.x. Possibly update the video with the new look of the page.

*Note*: since we are using Bootstrap 3 in the course, jQuery version needs to stay at 2.x to be compatible.

**Comment by BuchiGold** [comment]
please the bootstrap yakoov downloaded in the lecture video is different from the recent bootstrap on the page. what do i do?

**Comment by ychaikin** [comment]
> please the bootstrap yakoov downloaded in the lecture video is different from the recent bootstrap on the page. what do i do?

Download the version being used in the course instead of the latest one and ask questions like these on the course's forum, not here.

**Comment by CodingHung** [comment]
Sir, may I know where is the course's forum?
And the jQuery 1.x is no longer for download in the official website anymore.

**Comment by ychaikin** [comment]
@CodingHung 
<img width="348" alt="Screen Shot 2021-08-20 at 12 36 54 PM" src="https://user-images.githubusercontent.com/4999744/130265746-82031432-69a1-4a9b-973b-e6912ffbe726.png">
