### ISSUE TITLE
Bootstrap and CORS help needed

### ISSUE THREAD

**Issue by CoderZ820** [jhu-ep-coursera/fullstack-course4#344]
First of all I've tried using the forum, but get no response so here I go....

1) The Glyphicons do not work, I'm using BS3, but they don't work...help needed.

2) The categories images do not load, my code is identical to the example code, but the images do not load.  a 404 comes up and says BS is the reason.  Help needed.

3) Now that I've got all the JS written for dynamic loading, I'm getting a CORS error which makes sense because my laptop is foreign to the server being used.  Help needed.  I'm trying very hard to get this certificate, but the lack of help since this course is roughly 6 years old is getting very annoying, I paid the amount for the course, and now I want all the help that should come with it.

**Comment by rdlorenzo1972** [comment]
Hello. CORS, I didn't have to do for the assignment, but maybe the example provided in the lectures. There are several CORS videos (I had to learn for another project), here is the best one I found:
https://youtu.be/PNtFSVU-YTI

Please note, this may be out of scope for this course. I did on server side programming for different course.

**Comment by CoderZ820** [comment]
Thank you very much for the help.  I'll take a look when I cool down from
trying to get their code to work.

**Comment by CoderZ820** [comment]
Hello again, I found a fantastic solution to every cors issue I will ever
have so thank you very much for redirecting me to YouTube.   Do you have
any solutions for the 404 not found message I'm  getting....same message
for the glyphicons and images to the categories and the categories
themselves?  I would be most grateful!!!!

**Comment by ychaikin** [comment]
This is still not a place to ask questions or discuss solutions. Sorry.
