### ISSUE TITLE
Submit

### ISSUE THREAD

**Issue by KingSkyros** [jhu-ep-coursera/fullstack-course4#350]
Where do we submit our model-2 assignment? 

https://github.com/jhu-ep-coursera/fullstack-course4/tree/master/assignments/assignment2

**Comment by KingSkyros** [comment]
> Where do we submit all our assignments?
> 
> https://github.com/jhu-ep-coursera/fullstack-course4/tree/master/assignments

**Comment by ychaikin** [comment]
As the template said, this is NOT the place to ask questions.
