### ISSUE TITLE
submit error

### ISSUE THREAD

**Issue by Ballammal** [jhu-ep-coursera/fullstack-course4#352]
This is NOT the place to ask questions about the material or your issues with assignments from the Coursera course.

If you have a question or an issue, use the Coursera forum to ask that. (BUT FIRST, check the FAQ for the course: https://github.com/jhu-ep-coursera/fullstack-course4/blob/master/FAQ.md) Make the question as detailed as possible so people don't have to ask you for more details before answering your question.

Questions posted here as issues will simply be closed.

**Comment by Ballammal** [comment]
how to submit the assignment . i have not submit previous assignment . so i have to submit the asigment 3  4 5 assignments

**Comment by ychaikin** [comment]
Look at the comment above.
