### ISSUE TITLE
Add comment before each style selector to explain each pseudo-class. 

### ISSUE THREAD

**Issue by abhnerramos** [jhu-ep-coursera/fullstack-course4#366]
I read that before sending a PR with changes, I should suggest it here.

On lesson 15, we have pseudo-class selectors. Even though it was really well explained by professor @ychaikin , I think we could add a comment before each style selector describing what each pseudo-class does.

I already have everything settled, just waiting for your approval to send the PR. Please, let me know if I should do it.

**Comment by ychaikin** [comment]
I appreciate the thought! However, I think we'll leave it as is. Thanks!

**Comment by Akshat7666** [comment]
Yes you have the permission to proceed further, and send the PR
thank you for informing me about it.
