### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by K-Satya-K** [jhu-ep-coursera/fullstack-course4#388]
Hello sir, When I was practicing the URL in the same page concept I wrote my code as below, and when I clicked on the links it showed the file couldn't accessed. In the below, I attached my source code and the screenshot of the issue I am facing.
Waiting for your reply.

<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>links of content insame page</title>
<style>
h1{background-color:green;
color:yellow;
padding:6px}
</style>
</head>
<body>
<h1 style="text-align:center">POWER SYSTEM OPERATION AND CONTROL</h1>
<ol type="I">
<li><a href=".UNIT–I">unit-1</a></li>
<li><a href=".unit-2">unit-2</a></li>
<li><a href=".unit-3">unit-3</a></li>
<li><a href="unit-4">unit-4</a></li>
<li><a href="unit-5">unit-5</a></li></ol>
<h1 class="UNIT–I">" UNIT-I Economic Operation of Power Systems "</h1><p>Optimal operation of Generators in Thermal power stations, – Heat rate curve – Cost Curve – Incremental fuel and Production costs – Input–output characteristics – Optimum generation allocation with line losses neglected – Optimum generation allocation including the effect of transmission line losses – Loss Coefficients – General transmission line loss formula.</p>
<h1 class="unit-2">"UNIT–II: Hydrothermal Scheduling & Unit Commitment "</h1>
<p>Optimal scheduling of Hydrothermal System: Mathematical Formulation – Solution Technique. Optimal unit commitment problem – Need for unit commitment – Constraints in unit commitment – Cost function formulation – Solution methods – Priority ordering – Dynamic programming.</p>
<h1 class="unit-3">UNIT–III: Load Frequency Control-I </h1><p>Modeling of the steam turbine – Generator – Mathematical modeling of speed governing system – Transfer function – Necessity of keeping frequency constant – Definitions of Control area – Single area control system – Block diagram representation of an isolated power system – Steady state analysis – Dynamic response – Uncontrolled case. Proportional plus Integral control of the single area and its block diagram representation – Steady state response.</p>
<h1 class="unit-4">UNIT–IV: Load Frequency Control-II </h1>
<p>Block diagram development of Load Frequency Control of two area system uncontrolled case and controlled case. Tie-line bias control. Load Frequency Control and Economic dispatch control. </p>
<h1 class="unit-5">UNIT–V: Compensation in Power Systems</h1>
<p> Overview of Reactive Power control – Reactive Power compensation in transmission systems – Advantages and disadvantages of different types of compensating equipment for transmission systems – Load compensation – Specifications of load compensator – compensated transmission lines – Introduction of FACTS devices – Types of FACTS devices - Need of FACTS controllers.</p>
</body>
</html>

![image](https://github.com/jhu-ep-coursera/fullstack-course4/assets/142040113/f936a910-f56a-4fec-a261-e0d32de26a49)

**Comment by ychaikin** [comment]
This is NOT the place to ask questions about the material or your issues with assignments from the Coursera course.

If you have a question or an issue, use the Coursera forum to ask that. (BUT FIRST, check the FAQ for the course: https://github.com/jhu-ep-coursera/fullstack-course4/blob/master/FAQ.md) Make the question as detailed as possible so people don't have to ask you for more details before answering your question.

Questions posted here as issues will simply be closed.
