### ISSUE TITLE
Lectures 48-56 no longer contained in repo

### ISSUE THREAD

**Issue by gitmeto** [jhu-ep-coursera/fullstack-course4#400]
This is NOT the place to ask questions about the material or your issues with assignments from the Coursera course.

If you have a question or an issue, use the Coursera forum to ask that. (BUT FIRST, check the FAQ for the course: https://github.com/jhu-ep-coursera/fullstack-course4/blob/master/FAQ.md) Make the question as detailed as possible so people don't have to ask you for more details before answering your question.

Questions posted here as issues will simply be closed.

**Comment by ychaikin** [comment]
All available lecture slides are uploaded. Slides for 48 are missing and 49-56 don't use any slides to begin with.

**Comment by gitmeto** [comment]
Yeah I need to stop stunning late at night. I realized that after the fact..
