### ISSUE TITLE
Lecture 60

### ISSUE THREAD

**Issue by 4opper** [jhu-ep-coursera/fullstack-course4#43]
script.js
Doesn't work if innerHTML = responseText in this part of code.
 function (responseText) {
    document.querySelector("#main-content")
      .innerHTML = responseText;
  }
The result in browser is:  
![image](https://cloud.githubusercontent.com/assets/17986617/18765937/7f094756-8120-11e6-9206-0cbe5b704c07.png)
But if use responseText.response instead simple responseText, it works well.

**Comment by ychaikin** [comment]
@4opper Hi, could you provide some context to this? What lecture number are you in? What specific code are you running?

**Comment by 4opper** [comment]
It is lecture 60. I downloaded script.js from after folder in examples/Lecture60 and added this script in my index.html.

**Comment by ychaikin** [comment]
@4opper So, given that the lecture code works 100%, that would indicate that something didn't quite match between the original code its own context and when you moved it to your code. Seems like this pull request addresses an issue in your version of the code, not in the original lectures. 

I just verified and the original lecture code works 100% (both before and after folders).

**Comment by 4opper** [comment]
Sorry then. Course is awesome!)

**Comment by ychaikin** [comment]
@4opper Don't be sorry! I love the fact that you are trying to help to iron out any possible mistakes in the course content! Thank you for looking out for that!

All the best,
-Yaakov.

**Comment by 4opper** [comment]
@ychaikin Thanks for kind words!
