### ISSUE TITLE
Lecture 07/ codes needs correction

### ISSUE THREAD

**Issue by keshashah** [jhu-ep-coursera/fullstack-course4#45]
Hi, I am taking the coursera course - HTML, CSS, and Javascript for Web Developers. Found that in Lecture07/
1. The after-ordered-list file was missing
2. The before-ordered-list file had already tags inserted.

**Comment by keshashah** [comment]
I have a pull request for it - #44

**Comment by ychaikin** [comment]
@keshashah Thanks for contributing! Much appreciated!
