### ISSUE TITLE
examples, Lecture 10, wrong img src in images.html

### ISSUE THREAD

**Issue by liangxibing** [jhu-ep-coursera/fullstack-course4#47]
http://lorempixel.com/image_output/nature-q-c-640-480-1.jpg
should be:
http://lorempixel.com/output/nature-q-c-640-480-1.jpg

**Comment by ychaikin** [comment]
@liangxibing Yeah, they changed their API endpoint. I'll have to update it. Thanks!

Care to do a pull request with the fix? :-)

**Comment by liangxibing** [comment]
@ychaikin Of course, I have already pulled request: https://github.com/jhu-ep-coursera/fullstack-course4/pull/48
Thanks!

**Comment by ychaikin** [comment]
@liangxibing Thank you! Closing.
