### ISSUE TITLE
before and after example

### ISSUE THREAD

**Issue by Rajmono** [jhu-ep-coursera/fullstack-course4#5]
Before and after examples are the same. Not like in course vid with xxxxxx

https://github.com/jhu-ep-coursera/fullstack-course4/tree/master/examples/Lecture13

**Comment by ychaikin** [comment]
Thanks Rajmono! If you have time to fix that and create a pull request, that would be great. If not, no worries.

Thanks for submitting the ticket!

-Yaakov.

**Comment by ychaikin** [comment]
Was fixed here:
https://github.com/jhu-ep-coursera/fullstack-course4/pull/9
