### ISSUE TITLE
Assignment-3.md duplicate link

### ISSUE THREAD

**Issue by evgeny-pol** [jhu-ep-coursera/fullstack-course4#56]
File: fullstack-course4/assignments/assignment3/Assignment-3.md

Required assignment section, item 8:
The link to (http://getbootstrap.com/components/#navbar) repeats two times

**Comment by jasonwr** [comment]
@evgeny-pol Why not make a new pull request with this change? That way you can fix the problem and contribute to this repository.

**Comment by ychaikin** [comment]
Fixed.
