### ISSUE TITLE
The FAQ should include a section on grading

### ISSUE THREAD

**Issue by freeranger** [jhu-ep-coursera/fullstack-course4#61]
Q. I am late with my assignment, what should I do?
A. See the the week 1 section on grading [include link]

Q. The assignment I am reviewing has a link to the repository (or to somewhere else) and not to the deployed site.
A. Submitting the correct link is part of the assignment. You must grade the assignment 0 and explain in the comments why you have had to do this.

The above answer is the one we always give when people ask this question, and there have been a spate of them recently...

**Comment by naya65** [comment]
How do I create a folder in my repository? Please help!

**Comment by zoharch** [comment]
You can use desktop browser for that.
Just drag the folder into the git depository.

בתאריך 24 ביולי 2017 17:17,‏ "naya65" <notifications@github.com> כתב:

**Comment by wilfou90** [comment]
I have the difficulties to create a folder. I don't have the "gh-pages" which contains a folder already. what should I do?

**Comment by ychaikin** [comment]
@wilfou90 This isn't the place to ask questions. Ask them on the Coursera forum. The FAQ, which is part of this repository (https://github.com/jhu-ep-coursera/fullstack-course4/blob/master/FAQ.md) contains the answer about gh-pages.

**Comment by wilfou90** [comment]
Hello sir,
I am writing to you about the homework grading. I implemented my solution
which works well on my computer but for more than 3 days I try to generate
the URL which so far I have not found how to do. when I send my solution I
get zero, I would like to know if those who grade at least manage to
interpret code. it's disheartening. when I rate, I find several people in
my case, but I take the time to read their implementation solution to see
if it works before rating. there I no longer know if I continue to study or
not.
Best regards

Le ven. 8 mai 2020 à 23:02, Yaakov Chaikin <notifications@github.com> a
écrit :

**Comment by ychaikin** [comment]
If you feel your assignment is graded unfairly by 3 people, submit it again. If you get the same results, chances are it's your code that's wrong, not the people grading it.

Also, please do not post questions or correspondence here, as I've mentioned before.
