### ISSUE TITLE
Problem with Automatic Page generator 

### ISSUE THREAD

**Issue by kristy88** [jhu-ep-coursera/fullstack-course4#62]
I've made a repository at the GitHub, but when I go to the Settings there is no Automatic Page generator.

**Comment by ychaikin** [comment]
@kristy88, please ask questions on Coursera discussion forums. This is for reporting actually issues with the source code. 
[Here is the answer though](https://github.com/jhu-ep-coursera/fullstack-course4/blob/master/FAQ.md#q-where-is-the-launch-automatic-page-generator-button-the-page-looks-different-than-what-is-shown-in-the-video)
