### ISSUE TITLE
Don't have gh-pages and can't create pages automatically

### ISSUE THREAD

**Issue by binweng** [jhu-ep-coursera/fullstack-course4#65]
When I create repository, there is no gh-pages, I only have master branch. Is that okay I post assignment in master branch?

![screen shot 2017-01-11 at 10 30 01 pm](https://cloud.githubusercontent.com/assets/14224511/21875999/d358c9a6-d84d-11e6-991c-4a36e8c33add.png)

**Comment by freeranger** [comment]
Hi,

This mailing list is for mentors and staff communications only.
Help with the course is provided in the forums only so we would appreciate it if you use them in future.

The answer to your question is yes - master is fine

Thanks

Tony
