### ISSUE TITLE
where is coursera-test.git 

### ISSUE THREAD

**Issue by lightglams** [jhu-ep-coursera/fullstack-course4#72]
[where is coursera-test.git ? ](https://www.coursera.org/learn/html-css-javascript-for-web-developers/lecture/4T1t0/development-environment-setup-part-3-github-and-browser-sync)

06;42 time

**Comment by ychaikin** [comment]
Please ask questions on the forums on Coursera instead of creating an issue in the codebase.

**Comment by LATB85** [comment]
Hi jaakov
I'm sorry, I do not remember creating any issue, at least not intentionally
My apologies if I have caused any problems.

Best regards
Enviado desde mi iPhone
