### ISSUE TITLE
Browser sync installing issue 

### ISSUE THREAD

**Issue by KisDio89** [jhu-ep-coursera/fullstack-course4#74]
Hi everyone,

I have some issue about the browser sync, I am using a MacBook Pro with OS X Yosemite 10.10.5. I followed the instructions in the video, everything went great until this point. I installed the node, npm looks fine, after that I've done the sudo command, typed my password, press the enter, and thats where the problem is. (I tried without sudo as well, but it is the same)

The terminal says:

npm WARN deprecated node-uuid@1.4.8: Use uuid module instead

/Users/mac/npm-global/bin/browser-sync -> /Users/mac/npm-global/lib/node_modules/browser-sync/bin/browser-sync.js

/Users/mac/npm-global/lib

└── browser-sync@2.18.8

I attached a picture about the versions and this last message.

Can someone help me how can I fix this issue please? I'd like to carry on with the course, but I couldn't do it without the browsersync.

Thanks a lot in advance!

Krisztian Dios
<img width="1280" alt="kepernyofoto 2017-04-18 - 15 27 22" src="https://cloud.githubusercontent.com/assets/27523070/25136369/b4ad39ec-244c-11e7-9a90-d1a55f9a5bf0.png">

**Comment by freeranger** [comment]
Hi Krisztian

This is not the place to raise issues with installing software.  The course forum is the correct place for that.
The message you see is just a warning though - it does not mean browser-sync won't work.
Please raise anything further in the course forum.

Thanks.

**Comment by KisDio89** [comment]
Sorry about that, thanks.

**Comment by freeranger** [comment]
@ychaikin please close this - it is not a repo issue
