### ISSUE TITLE
Design Mockup 

### ISSUE THREAD

**Issue by adilash** [jhu-ep-coursera/fullstack-course4#75]
Where can i find the png file of design mockup?

Thanks

**Comment by ychaikin** [comment]
I don't believe I published them. You don't really need them. 

Also, please ask questions in Corusera forums. This is not a medium for questions.

All the best,
-Yaakov.

**Comment by adilash** [comment]
i cant seem to find the Coursra forums..

**Comment by thuyihan1206** [comment]
Just right in the Coursera site:

https://www.coursera.org/learn/html-css-javascript-for-web-developers/discussions


--
Evan (Chi Pang) Chan
chchan1206@gmail.com
