### ISSUE TITLE
Git hub doesn't create gh-pages branch automatically anymore

### ISSUE THREAD

**Issue by LexSombra** [jhu-ep-coursera/fullstack-course4#76]
In the video "Development Setup Part 3", when the website is created, git hub automatically creates a gh-branch and puts index.html and some style and json files there.
At the moment, it doesn't do that anymore.
When I tried to create a website, git hub created it in the master branch and just added a .yml file to it.
This might me a little confusing for novices.

Thank you!

**Comment by ychaikin** [comment]
Please don't ask questions through creating issues. That's what Coursera forums are for.

Also, the FAQ is published as part of the course and part of that FAQ is this:
https://github.com/jhu-ep-coursera/fullstack-course4/blob/master/FAQ.md#q-where-is-the-launch-automatic-page-generator-button-the-page-looks-different-than-what-is-shown-in-the-video

All the best,
-Yaakov.
