### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by elnazde** [jhu-ep-coursera/fullstack-course4#77]
Hi there,

I just started the course and I can't go past the intro videos because I keep getting this message "FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory" in Terminal, I looked online and tried to increase my memory limit but it's saying to do this at the root of the project. My webpage also doesn't load correctly, it just gives me a listing directory but my code looks fine when I compare. As a newbie, I don't quite know how to fix this and would appreciate any help so I can move to the next step!

Thank you!

**Comment by ychaikin** [comment]
Please use Coursera forums to ask questions instead of opening issues in the repo.
