### ISSUE TITLE
error 403

### ISSUE THREAD

**Issue by Giorgiob89** [jhu-ep-coursera/fullstack-course4#89]
Hello, 

The first time that I tried to update the index.html file to the git, after typing the command git push, I misspelled the password and now after trying to type the command git push to load the file into the git I get the error 403. How can I solve it?
Thanks

**Comment by ychaikin** [comment]
Please ask questions on the Coursera forum. GitHub issues for this repo is only here to report code problems (if you find any). Thanks!
